### ISSUE TITLE
Pages bullets clickable

### ISSUE THREAD

**Issue by daniesy** [TanguyAladenise/TAPageControl#1]
Pages bullets are clickable in the example, but don't change the page.

**Comment by TanguyAladenise** [comment]
Hi,

My bad, I forgot implementing a delegate on this :/
The PageControl will never move to the page for you though. Your controller should handle this via a delegate for example.
For the time being I suggest you use KVO on currentPage.
I will fix this.
Thanks for the input.

**Comment by daniesy** [comment]
No problem! You're welcome! I thank you!

**Comment by TanguyAladenise** [comment]
I fix the issue and added a delegate, so both KVO and delegate can help you work with bullet touch event.
The example project has been updated to work with middle carousel.
Just update your pod if you use cocoapods.
I hope it will answer your need ;)
